spring.application.name=KinalApplication
server.port=9095


#Connection to MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/DB_Clients_in5av?createDatabaseIfNotExist=true
spring.datasource.username=IN5AV
spring.datasource.password=!+admin5av

#JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG



